config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :show, :create] do
    resources :tries, only: [:create]
  end

  get 'welcome/index'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/work_picker.rb
module WordPicker
  UNIX_WORDS_PATH = '/usr/share/dict/words'
  def pick
    File.read(UNIX_WORDS_PATH).split.sample
  end
end

app/models/game.rb
class Game < ApplicationRecord
  # Associations
  has_many :plays
  has_many :players, through: :plays

  # Validations
  validates :secret,
            presence: true,
            format: { with: /\A[a-zA-Z]+\z/ }

  validates :lives,
            presence: true,
            numericality: { only_integer: true,
                            greater_than_or_equal_to: 0 }

  validates :tries,
            format: { with: /\A[a-zA-Z]*\z/, message: "input must be a letter" }
  validate :check_duplicates

  def check_duplicates
    if tries != nil
      duplicates = tries.each_char.detect { |char| tries.count(char) > 1 }
      errors[:tries] << "Already tried '#{duplicates}'" if duplicates
    end
  end

  # Callbacks
  before_validation :init_secret, on: :create

  def init_secret
    self.secret ||= 'horseshit'
  end

  #
  def lost?
    lives <= 0
  end

  def won?
    (secret.chars - tries.chars).empty?
  end

  def secret_word_masked
    secret.each_char.map { |char| tries.include?(char) ? char : nil }
  end

  def failed_try?(try)
    # Bad input is not a failed try: it's a invalid try.
    valid? and not secret.include?(try)
  end

  def set_next_turn
    current_play.set_active!(false)

    plays_ordered_by_id = plays.order(:id)
    first_play = plays_ordered_by_id.first
    next_play = plays_ordered_by_id.find(&method(:next_valid?)) || first_play

    next_play.set_active!(true)
  end

  def guess(try)
    self.tries << try

    if failed_try?(try)
      current_play.lose_a_life!
      set_next_turn
    end
  end

  def guesses_already_made?
    tries.length > 0
  end

  def add_player(player_id)
    self.players << Player.find(player_id)
  end

  def set_first_player!
    plays.take.set_active!(true)
  end

  def current_player
    Player.find(current_play.player_id)
  end

  def current_play
    plays.find_by(active: true)
  end
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :game
  belongs_to :player

  def lose_a_life!
    self.lives -= 1
    save!
  end

  def next_valid?(previous_play_id)
    id > previous_play_id and lives > 0
  end

  def set_active!(active_state)
    self.active = active_state
    save!
  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :plays
  has_many :games, through: :plays

  validates :name,
            presence: true,
            format: { with: /\A.+\z/ }
  validates :color,
            format: { with: /\A\#[0-9a-fA-F]{6}\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def create
    @game = Game.new
    
    params[:game][:player_ids].each do |player_id|
      @game.add_player(player_id)
    end
    
    if @game.save
      @game.set_first_player!
      redirect_to @game
    else
      redirect_to games_path, notice: @game.errors
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.all
  end

  def create
    @player = Player.new(player_params)

    if @player.save(player_params)
      redirect_to players_path
    else
      redirect_to players_path, notice: @player.errors
    end
  end

  private

  def player_params
    params.require(:player).permit(:name, :color)
  end
end

app/controllers/tries_controller.rb
class TriesController < ApplicationController
  def create
    try = tries_params
    game = Game.find(params[:game_id])

    game.guess(try)

    if game.save
      redirect_to game
    else
      redirect_to game, notice: game.errors[:tries]
    end
  end

  private

  def tries_params
    params.require(:guess)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def format_masked_word(mask)
    mask.map { |char| char || '_' }.join(' ')
  end

  def format_tries(game)
    game.tries.chars.join(', ')
  end

  def show_lives_image(game)
    image_tag "hang#{7 - game.lives}"
  end

  def show_lives_sentence(game)
    "#{pluralize(game.lives, 'life')} remaining."
  end

  def show_status(game)
    if game.won?
      "Won"
    elsif game.lost?
      "Lost"
    else
      "In progress"
    end
  end

  def render_game_status(game)
    if game.won?
      render partial: 'won'
    elsif game.lost?
      render partial: 'lost'
    else
      render partial: 'in_progress'
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/tries_helper.rb
module TriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/_error.html.erb
<p>
    <% if flash[:notice] %>
        <div class="flashnotice">
            <% flash[:notice].each do |notice| %>
                <%= "#{notice}" %>
            <% end %>
        </div>
    <% end %>
</p>

app/views/games/_in_progress.html.erb
<h2><%= format_masked_word(@game.secret_word_masked) %></h2>

<%= form_tag(game_tries_path(@game), :method => 'post') do  %>
    <%= label_tag 'Your guess'%>
    <%= text_field_tag :guess %>
    <%= submit_tag "Guess" %>
<% end %>

<%= render partial: 'error' %>

<% if @game.guesses_already_made? %>
    <p>
        You've already tried <%= format_tries(@game) %>.
    </p>
<% end %>

app/views/games/_lost.html.erb
<p>
    You've lost the game!
    The secret word was "<%= @game.secret %>".
    You tried <%= format_tries(@game)%>.
</p>

app/views/games/_status.html.erb
<%= render_game_status(@game) %>

app/views/games/_won.html.erb
<p>
    You've won the game! Congrats!
</p>

app/views/games/index.html.erb
<% content_for :title, "List of hangman games" %>

<h1>List of games</h1>

<table>
    <tr>
        <th>Game #</th>
        <th>Status</th>
        <th>Lives</th>
        <th>Secret word</th>
    </tr>
    <% @games.each do |game| %>
        <tr>
            <td><%= game.id %></td>
            <td><%= show_status(game) %></td>
            <td><%= pluralize(game.lives, 'life') %></td>
            <td><%= game.secret %></td>
            <td><%= link_to 'Join', game_path(game) %></td>
        </tr>
    <% end %>
</table>

<%= render partial: 'error' %>

<%= link_to 'Create a new game', games_path, method: :post %>

app/views/games/new.html.erb
<h1>New game</h1>

Which players?

    <%= form_for :game, url: games_path do |f| %>
        <% Player.all.each do |player| %>
            <%= check_box_tag :player_ids,
            player.id,
            false, # No player selected by default
            :name => 'game[player_ids][]'
            %>
            <%= player.name %>
        <% end %>

        <%= f.submit 'Create game' %>
    <% end %>
</ul>
<%= link_to 'Back to games', games_path %>

app/views/games/show.html.erb
<% content_for :title, "Game ##{@game.id}" %>

<h1>Game #<%= @game.id %></h1>

<%= show_lives_image(@game) %>
<%= show_lives_sentence(@game) %>

<%= render partial: 'status' %>

<%= link_to 'Back to games', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HangmanRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/games.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<h1>Players</h1>

<table>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Color</th>
    </tr>
    <% @players.each do |player| %>
        <tr>
            <td><%= player.id %></td>
            <td><%= player.name %></td>
            <td><%= player.color %></td>
        </tr>
    <% end %>
</table>

<%= link_to 'Create a new player', new_player_path %><br>
<%= link_to 'Back to Welcome page', welcome_index_path %>

app/views/players/new.html.erb
<h1>Here comes a new challenger</h1>

<%= form_for :player, url: players_path do |f| %>
    <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :color %>
        <%= f.color_field :color %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

<%= link_to "Back to index", players_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Hangman-on-Rails!</h1>

<%= link_to 'List of games', controller: 'games' %><br>
<%= link_to 'List of players', controller: 'players' %>